theme: jekyll-theme-slate

title: HackaTUM 2021
description: Helpful resources, links and information for the hackaTUM 2021 challenges Azure rsources, \n links and information for /n the hackaTUM 2021 <br> Azure Walk-Through

show_downloads: false
