theme: jekyll-theme-slate

title: HackaTUM 2021
description: Helpful resources, links and information for the hackaTUM 2021 challenges Azure rsources, links and information for the hackaTUM 2021
Azure Walk-Through

show_downloads: false
